### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/proc/28953/task/28953/children'

### ISSUE THREAD

**Issue by CapeCrusader321** [CapeCrusader321/Lutris-snap#12]
The Following Error is Generated while installing exe files with lutris wine.

```
Traceback (most recent call last):
  File "/snap/lutris/52/usr/share/lutris/bin/lutris-wrapper", line 202, in <module>
    main()
  File "/snap/lutris/52/usr/share/lutris/bin/lutris-wrapper", line 167, in main
    if not watcher.is_alive():
  File "/snap/lutris/52/usr/lib/python3/dist-packages/lutris/util/process_watcher.py", line 75, in is_alive
    return next(self.iterate_processes(), None) is not None
  File "/snap/lutris/52/usr/lib/python3/dist-packages/lutris/util/process_watcher.py", line 64, in iterate_processes
    for child in self.iterate_children():
  File "/snap/lutris/52/usr/lib/python3/dist-packages/lutris/util/process.py", line 131, in iter_children
    for child in self.children:
  File "/snap/lutris/52/usr/lib/python3/dist-packages/lutris/util/process.py", line 125, in children
    for child_pid in self.get_children_pids_of_thread(tid):
  File "/snap/lutris/52/usr/lib/python3/dist-packages/lutris/util/process.py", line 71, in get_children_pids_of_thread
    with open(children_path, encoding='utf-8') as children_file:
```

**Comment by CapeCrusader321** [comment]
Cant Say If This can be fixed ?? seems similar to #4

**Comment by CapeCrusader321** [comment]
Tried setting TMPDIR To a accessible place, hope that fixes it, if not then its beyond my scope of repair.

**Comment by CapeCrusader321** [comment]
Be It Wine or Citra, this error is omnipresent ..

'''
Traceback (most recent call last):
  File "/snap/lutris/64/usr/share/lutris/bin/lutris-wrapper", line 202, in <module>
    main()
  File "/snap/lutris/64/usr/share/lutris/bin/lutris-wrapper", line 167, in main
    if not watcher.is_alive():
  File "/snap/lutris/64/usr/lib/python3/dist-packages/lutris/util/process_watcher.py", line 75, in is_alive
    return next(self.iterate_processes(), None) is not None
  File "/snap/lutris/64/usr/lib/python3/dist-packages/lutris/util/process_watcher.py", line 64, in iterate_processes
    for child in self.iterate_children():
  File "/snap/lutris/64/usr/lib/python3/dist-packages/lutris/util/process.py", line 131, in iter_children
    for child in self.children:
  File "/snap/lutris/64/usr/lib/python3/dist-packages/lutris/util/process.py", line 125, in children
    for child_pid in self.get_children_pids_of_thread(tid):
  File "/snap/lutris/64/usr/lib/python3/dist-packages/lutris/util/process.py", line 71, in get_children_pids_of_thread
    with open(children_path, encoding='utf-8') as children_file:
PermissionError: [Errno 13] Permission denied: '/proc/19046/task/19046/children'
'''

**Comment by CapeCrusader321** [comment]
'''
PermissionError: [Errno 13] Permission denied: '/proc/7126/task/7126/children'
2023-05-23 19:18:40,183: No file /tmp/lutris-625bbbd7-020a-4c7a-8d5c-1705dfec8fcb
'''
