### ISSUE TITLE
Cant Run Citra Emulator Used For Nintendo 3DS.

### ISSUE THREAD

**Issue by CapeCrusader321** [CapeCrusader321/Lutris-snap#22]
'''
Started initial process 19049 from /home/sam/snap/lutris/64/.local/share/lutris/runners/citra/citra-qt
Start monitoring process.
Traceback (most recent call last):
  File "/snap/lutris/64/usr/share/lutris/bin/lutris-wrapper", line 202, in <module>
    main()
  File "/snap/lutris/64/usr/share/lutris/bin/lutris-wrapper", line 167, in main
    if not watcher.is_alive():
  File "/snap/lutris/64/usr/lib/python3/dist-packages/lutris/util/process_watcher.py", line 75, in is_alive
    return next(self.iterate_processes(), None) is not None
  File "/snap/lutris/64/usr/lib/python3/dist-packages/lutris/util/process_watcher.py", line 64, in iterate_processes
    for child in self.iterate_children():
  File "/snap/lutris/64/usr/lib/python3/dist-packages/lutris/util/process.py", line 131, in iter_children
    for child in self.children:
  File "/snap/lutris/64/usr/lib/python3/dist-packages/lutris/util/process.py", line 125, in children
    for child_pid in self.get_children_pids_of_thread(tid):
  File "/snap/lutris/64/usr/lib/python3/dist-packages/lutris/util/process.py", line 71, in get_children_pids_of_thread
    with open(children_path, encoding='utf-8') as children_file:
PermissionError: [Errno 13] Permission denied: '/proc/19046/task/19046/children'
fuse: failed to open /dev/fuse: Operation not permitted

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
2023-05-23 15:48:14,383: No file /tmp/lutris-f9da2d9f-9f55-4bcc-8d87-b9b3585e4ca3
"'

**Comment by CapeCrusader321** [comment]
Successfully solved by adding or passing this ;
export APPIMAGE_EXTRACT_AND_RUN=1
