### ISSUE TITLE
Lutris wont open/run in Ubuntu 22.10

### ISSUE THREAD

**Issue by Szymonejros** [CapeCrusader321/Lutris-snap#26]
I've installed Lutris from Ubuntu Software(--> snap shop) and it wont open

**Comment by CapeCrusader321** [comment]
@Szymonejros  I need more details, perhaps please do the following :

```
1) sudo snap remove lutris --purge
2) rm -r ~/snap/lutris
3) exec $SHELL
4) sudo snap install lutris --edge
5) exec $SHELL
6) From the terminal, lutris
7) Paste all the text that appears in the terminal while opening lutris.

**Comment by Eleuthar** [comment]
Warning: Schema “org.gnome.system.locale” has path “/system/locale/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy” has path “/system/proxy/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.http” has path “/system/proxy/http/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.https” has path “/system/proxy/https/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.ftp” has path “/system/proxy/ftp/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.socks” has path “/system/proxy/socks/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
ERROR:dbus.proxies:Introspect error on :1.36:/org/gnome/Mutter/DisplayConfig: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.125" (uid=1000 pid=11661 comm="python3 /snap/lutris/70/usr/bin/lutris " label="snap.lutris.lutris (enforce)") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.36" (uid=1000 pid=2078 comm="/usr/bin/gnome-shell " label="unconfined")
2023-05-25 20:24:35,402: Starting Lutris 0.5.13
INFO:lutris.util.log:Starting Lutris 0.5.13
Traceback (most recent call last):
  File "/snap/lutris/70/usr/lib/python3/dist-packages/lutris/gui/application.py", line 436, in do_command_line
    run_all_checks()
  File "/snap/lutris/70/usr/lib/python3/dist-packages/lutris/startup.py", line 189, in run_all_checks
    check_driver()
  File "/snap/lutris/70/usr/lib/python3/dist-packages/lutris/startup.py", line 63, in check_driver
    driver_info = drivers.get_nvidia_driver_info()
  File "/snap/lutris/70/usr/lib/python3/dist-packages/lutris/util/graphics/drivers.py", line 18, in get_nvidia_driver_info
    with open(version_file_path, encoding='utf-8') as version_file:
PermissionError: [Errno 13] Permission denied: '/proc/driver/nvidia/version'
2023-05-25 20:24:36,013: Shutting down Lutris
INFO:lutris.util.log:Shutting down Lutris

**Comment by Eleuthar** [comment]
And providing sudo privilege:


$ sudo lutris
mkdir: cannot create directory '/run/user/0': Permission denied
Warning: Schema “org.gnome.system.locale” has path “/system/locale/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy” has path “/system/proxy/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.http” has path “/system/proxy/http/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.https” has path “/system/proxy/https/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.ftp” has path “/system/proxy/ftp/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.socks” has path “/system/proxy/socks/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Error: unable to open display :1
2023-05-25 20:25:38,009: ['glxinfo', '-B'] command failed: Command '['glxinfo', '-B']' returned non-zero exit status 255.
2023-05-25 20:25:38,009: No available glxinfo output
2023-05-25 20:25:38,009: Invalid glxinfo received
Authorization required, but no authorization protocol specified

(lutris:11928): Gtk-CRITICAL **: 20:25:38.652: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/snap/lutris/70/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/snap/lutris/70/usr/lib/python3/dist-packages/lutris/gui/application.py", line 58, in <module>
    from .lutriswindow import LutrisWindow
  File "/snap/lutris/70/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 19, in <module>
    from lutris.gui.config.preferences_dialog import PreferencesDialog
  File "/snap/lutris/70/usr/lib/python3/dist-packages/lutris/gui/config/preferences_dialog.py", line 10, in <module>
    from lutris.gui.config.runners_box import RunnersBox
  File "/snap/lutris/70/usr/lib/python3/dist-packages/lutris/gui/config/runners_box.py", line 8, in <module>
    from lutris.gui.config.runner_box import RunnerBox
  File "/snap/lutris/70/usr/lib/python3/dist-packages/lutris/gui/config/runner_box.py", line 9, in <module>
    from lutris.gui.dialogs.runner_install import RunnerInstallDialog
  File "/snap/lutris/70/usr/lib/python3/dist-packages/lutris/gui/dialogs/runner_install.py", line 51, in <module>
    class RunnerInstallDialog(ModelessDialog):
  File "/snap/lutris/70/usr/lib/python3/dist-packages/lutris/gui/dialogs/runner_install.py", line 61, in RunnerInstallDialog
    if has_stock_icon("software-installed-symbolic") else "wine-symbolic"
  File "/snap/lutris/70/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 155, in has_stock_icon
    return theme.has_icon(name)
AttributeError: 'NoneType' object has no attribute 'has_icon'

**Comment by CapeCrusader321** [comment]
@Eleuthar  Never use sudo fro running snaps, please see --> https://github.com/CapeCrusader321/Lutris-snap/issues/4

This is an issue with the upstream am constantly looking upon these.

**Comment by CapeCrusader321** [comment]
Closing as #4 is fixed.
