### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'present' 0.5.13 devmode

### ISSUE THREAD

**Issue by brunosc** [CapeCrusader321/Lutris-snap#28]
**Bug description**

I tried to install [0.5.13](https://github.com/lutris/lutris/releases/tag/v0.5.13) but got this same issue https://github.com/lutris/lutris/issues/4858.

After reading this one https://github.com/CapeCrusader321/Lutris-snap/issues/4, I tried to install the snap with dev mode (`snap install lutris --edge --devmode`) but now I'm getting another error:

```
bruno@linux:~$ lutris
Warning: Schema “org.gnome.system.locale” has path “/system/locale/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy” has path “/system/proxy/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.http” has path “/system/proxy/http/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.https” has path “/system/proxy/https/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.ftp” has path “/system/proxy/ftp/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.socks” has path “/system/proxy/socks/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
2023-06-01 14:53:44,686: Starting Lutris 0.5.13
2023-06-01 14:53:44,765: Using NVIDIA drivers 530.41.03 for x86_64
2023-06-01 14:53:44,766: GPU: NVIDIA GeForce MX550
2023-06-01 14:53:44,767: GPU: 10DE:1F9F 17AA:22E9 (nvidia drivers)
2023-06-01 14:53:44,767: GPU: 8086:46A6 17AA:22E9 (i915 drivers)
Traceback (most recent call last):
  File "/snap/lutris/74/usr/lib/python3/dist-packages/lutris/gui/application.py", line 291, in do_activate
    self.window = LutrisWindow(application=self)
  File "/snap/lutris/74/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 124, in __init__
    self.sidebar.initialize_rows()
  File "/snap/lutris/74/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 397, in initialize_rows
    self.update_rows()
  File "/snap/lutris/74/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 476, in update_rows
    self.installed_runners = [runner.name for runner in runners.get_installed()]
  File "/snap/lutris/74/usr/lib/python3/dist-packages/lutris/runners/__init__.py", line 102, in get_installed
    if runner.is_installed():
  File "/snap/lutris/74/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 476, in is_installed
    return self.flatpak_id and flatpak.is_app_installed(self.flatpak_id)
  File "/snap/lutris/74/usr/lib/python3/dist-packages/lutris/util/flatpak.py", line 53, in is_app_installed
    for app in get_installed_apps():
  File "/snap/lutris/74/usr/lib/python3/dist-packages/lutris/util/flatpak.py", line 28, in get_installed_apps
    command = get_command() + ["list"]
  File "/snap/lutris/74/usr/lib/python3/dist-packages/lutris/util/flatpak.py", line 22, in get_command
    if "flatpak-spawn" in exe:
TypeError: argument of type 'NoneType' is not iterable
2023-06-01 14:53:44,898: Running migration: mess_to_mame
2023-06-01 14:53:44,899: Running migration: migrate_hidden_ids
2023-06-01 14:53:44,900: Running migration: migrate_steam_appids
2023-06-01 14:53:44,901: Running migration: migrate_banners
2023-06-01 14:53:44,924: Running migration: retrieve_discord_appids
2023-06-01 14:53:44,925: Updating Games Discord APP ID's
2023-06-01 14:54:00,112: Runtime eac_runtime is not available locally
2023-06-01 14:54:00,115: Runtime dxvk-cache-tool is not available locally
2023-06-01 14:54:00,116: Runtime Ubuntu-18.04-x86_64 is not available locally
2023-06-01 14:54:00,117: Runtime Ubuntu-18.04-i686 is not available locally
2023-06-01 14:54:00,121: Runtime winetricks is not available locally
2023-06-01 14:54:00,130: Runtime network-tools is not available locally
2023-06-01 14:54:00,132: Runtime battleye_runtime is not available locally
2023-06-01 14:54:00,134: Runtime gamecontrollerdb is not available locally
2023-06-01 14:54:00,136: Runtime p7zip is not available locally
2023-06-01 14:54:00,138: Runtime innoextract-1.9-linux is not available locally
2023-06-01 14:54:02,140: Non existent path: /home/bruno/snap/lutris/74/.local/share/lutris/runtime/winetricks
2023-06-01 14:54:02,528: Non existent path: /home/bruno/snap/lutris/74/.local/share/lutris/runtime/eac_runtime
2023-06-01 14:54:02,751: Non existent path: /home/bruno/snap/lutris/74/.local/share/lutris/runtime/gamecontrollerdb
2023-06-01 14:54:03,032: Non existent path: /home/bruno/snap/lutris/74/.local/share/lutris/runtime/dxvk-cache-tool
2023-06-01 14:54:04,154: Non existent path: /home/bruno/snap/lutris/74/.local/share/lutris/runtime/network-tools
2023-06-01 14:54:06,077: Non existent path: /home/bruno/snap/lutris/74/.local/share/lutris/runtime/innoextract-1.9-linux
2023-06-01 14:54:06,273: Non existent path: /home/bruno/snap/lutris/74/.local/share/lutris/runtime/p7zip
2023-06-01 14:54:10,398: Non existent path: /home/bruno/snap/lutris/74/.local/share/lutris/runtime/battleye_runtime
2023-06-01 14:54:29,514: Non existent path: /home/bruno/snap/lutris/74/.local/share/lutris/runtime/Ubuntu-18.04-x86_64
2023-06-01 14:54:32,232: Non existent path: /home/bruno/snap/lutris/74/.local/share/lutris/runtime/Ubuntu-18.04-i686
2023-06-01 14:54:33,708: Runtime update completed.
2023-06-01 14:54:34,033: Downloading DXVK v2.2...
2023-06-01 14:54:34,034: Downloading https://github.com/lutris/dxvk/releases/download/v2.2/dxvk-2.2.tar.xz to /home/bruno/snap/lutris/74/.local/share/lutris/runtime/dxvk/dxvk-2.2.tar.xz
2023-06-01 14:54:35,898: Extracting /home/bruno/snap/lutris/74/.local/share/lutris/runtime/dxvk/dxvk-2.2.tar.xz to /home/bruno/snap/lutris/74/.local/share/lutris/runtime/dxvk/v2.2
2023-06-01 14:54:36,279: Downloading DXVK-NVAPI v0.6.3...
2023-06-01 14:54:36,280: Downloading https://github.com/lutris/dxvk-nvapi/releases/download/v0.6.3/dxvk-nvapi-v0.6.3.tar.xz to /home/bruno/snap/lutris/74/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.3.tar.xz
2023-06-01 14:54:37,577: Extracting /home/bruno/snap/lutris/74/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.3.tar.xz to /home/bruno/snap/lutris/74/.local/share/lutris/runtime/dxvk-nvapi/v0.6.3
2023-06-01 14:54:37,879: Downloading VKD3D v2.9...
2023-06-01 14:54:37,881: Downloading https://github.com/lutris/vkd3d/releases/download/v2.9/vkd3d-v2.9.tar.xz to /home/bruno/snap/lutris/74/.local/share/lutris/runtime/vkd3d/vkd3d-v2.9.tar.xz
2023-06-01 14:54:39,052: Extracting /home/bruno/snap/lutris/74/.local/share/lutris/runtime/vkd3d/vkd3d-v2.9.tar.xz to /home/bruno/snap/lutris/74/.local/share/lutris/runtime/vkd3d/v2.9
2023-06-01 14:54:39,305: Downloading D3D Extras v2...
2023-06-01 14:54:39,306: Downloading https://github.com/lutris/d3d_extras/releases/download/v2/v2.tar.xz to /home/bruno/snap/lutris/74/.local/share/lutris/runtime/d3d_extras/v2.tar.xz
2023-06-01 14:54:52,653: Extracting /home/bruno/snap/lutris/74/.local/share/lutris/runtime/d3d_extras/v2.tar.xz to /home/bruno/snap/lutris/74/.local/share/lutris/runtime/d3d_extras/v2
2023-06-01 14:54:54,445: Downloading dgvoodoo2 v2.8...
2023-06-01 14:54:54,446: Downloading https://github.com/lutris/dgvoodoo2/releases/download/v2.8/dgvoodoo2-v2.8.tar.xz to /home/bruno/snap/lutris/74/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2-v2.8.tar.xz
2023-06-01 14:54:55,167: Extracting /home/bruno/snap/lutris/74/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2-v2.8.tar.xz to /home/bruno/snap/lutris/74/.local/share/lutris/runtime/dgvoodoo2/v2.8
2023-06-01 14:54:55,222: Startup complete
Traceback (most recent call last):
  File "/snap/lutris/74/usr/lib/python3/dist-packages/lutris/gui/application.py", line 657, in do_command_line
    self.window.present()
AttributeError: 'NoneType' object has no attribute 'present'
```

Dependencies
```
Python 3.10.6
wine-8.0.1
```

Am I missing something else? Thanks.

**Comment by CapeCrusader321** [comment]
@brunosc  This is happening most probably due to snapcraft mechanism stripping off dependencies of lutris that are already present in the gnome-sdk etc. , but the problem with lutris is that it doesnt use those libs from gnome-sdk properly and thats why i had in first place staged them exclusively with the snap but i think they are being removed off during the review stage to make the snaplighter, (earlier the snap was 200 mb but after stripping its 117 mb)

**Comment by brunosc** [comment]
Got it. I will try again the deb package.
Thank you for your attention.

**Comment by CapeCrusader321** [comment]
Reopening this i need this for better insights to fix this problem, this has occurred due to lutris trying to launch flatpak runners which isnt present in snap sandbox.

See --> #29

**Comment by CapeCrusader321** [comment]
@brunosc  Happy to report this has been fixed, if you wish, you can retest the snap, but this time do the following ;

```
1) sudo snap remove lutris --purge
2) sudo snap install lutris --edge # Dont use dev mode, the other issue is also fixed
```
