### ISSUE TITLE
Upstream Patch For Flatpak May have broken Snap ??

### ISSUE THREAD

**Issue by CapeCrusader321** [CapeCrusader321/Lutris-snap#29]
```
(lutris:13870): IBUS-WARNING **: 11:13:52.863: Failed to mkdir /home/sam/snap/lutris/75/.config/ibus/bus: Not a directory
Traceback (most recent call last):
  File "/snap/lutris/75/usr/lib/python3/dist-packages/lutris/gui/application.py", line 291, in do_activate
    self.window = LutrisWindow(application=self)
  File "/snap/lutris/75/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 124, in __init__
    self.sidebar.initialize_rows()
  File "/snap/lutris/75/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 440, in initialize_rows
    self.update_rows()
  File "/snap/lutris/75/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 527, in update_rows
    self.installed_runners = [runner.name for runner in runners.get_installed()]
  File "/snap/lutris/75/usr/lib/python3/dist-packages/lutris/runners/__init__.py", line 102, in get_installed
    if runner.is_installed():
  File "/snap/lutris/75/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 476, in is_installed
    return self.flatpak_id and flatpak.is_app_installed(self.flatpak_id)
  File "/snap/lutris/75/usr/lib/python3/dist-packages/lutris/util/flatpak.py", line 53, in is_app_installed
    for app in get_installed_apps():
  File "/snap/lutris/75/usr/lib/python3/dist-packages/lutris/util/flatpak.py", line 28, in get_installed_apps
    command = get_command() + ["list"]
  File "/snap/lutris/75/usr/lib/python3/dist-packages/lutris/util/flatpak.py", line 22, in get_command
    if "flatpak-spawn" in exe:
TypeError: argument of type 'NoneType' is not iterable
```

Upstream Commit -->  https://github.com/lutris/lutris/commit/d4c3f8223514e7ae17b44bef28398532e03edb02

**Comment by CapeCrusader321** [comment]
Fixed By Upstream --> https://github.com/lutris/lutris/commit/d556c7d857ad73cd85cde68831e8da0a116df769
